### ISSUE TITLE
Calibrated branch length

### ISSUE THREAD

**Issue by Angel-Fernandez** [fiji/AnalyzeSkeleton#3]
Hi @iarganda, @hinerm 

I'm Angel.  How skeleton analyze calculates the calibrated branch length?

Thanks and best regards

**Comment by iarganda** [comment]
Hello @Angel-Fernandez ,

The calibrated length is calculated as the sum of the Euclidean distances of all consecutive voxels in a branch. It is calibrated because it takes into account the volume calibration to calculate the distances.

Does it make sense?

**Comment by Angel-Fernandez** [comment]
Ok thanks
