### ISSUE TITLE
Bug in Analyze Skeleton (2D/3D)

### ISSUE THREAD

**Issue by ctrueden** [fiji/AnalyzeSkeleton#4]
From [Fiji BugZilla issue #1164](http://fiji.sc/bugzilla/show_bug.cgi?id=1164):
> when skeletonizing images it can happen that the skeletons are only 1px. I think that the spx and spy values in the Results are not correct. I can´t comment on spy, since I only have 2D data.
> The following macro illustrates this. 
> e.g. spx and spy values in row 4 and 5 are identical. also in row 9 and 10, and ......
>
> ```javascript
> run("Blobs (25K)");
> run("Make Binary");
> run("Skeletonize (2D/3D)");
> run("Analyze Skeleton (2D/3D)", "prune=none calculate show");
> selectWindow("Results");
> ```

**Comment by iarganda** [comment]
Fixed with the new release (v2.0.5). Thanks for reporting!
