### ISSUE TITLE
Tagged skeleton doesn't show a time axis

### ISSUE THREAD

**Issue by rimadoma** [fiji/AnalyzeSkeleton#7]
When the input skeleton image has a time dimension the tagged skeleton image doesn't show it

**Steps to reproduce**
1. Open "mitosis.tif" (File>Open Samples>Mitosis)
2. Remove channels (Image>Color>Stack to RBG)
3. Binarise image (Process>Binary>Make Binary)
4. Run Skeletonize
5. Run Analyze Skeleton

**Comment by ctrueden** [comment]
I merged #8, so hopefully this is resolved now. Thanks again Richard.
